[2025-03-30T23:35:21.815+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T23:35:21.862+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_users_to_database.load_users_to_sql manual__2025-03-30T23:35:10.238474+00:00 [queued]>
[2025-03-30T23:35:21.890+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_users_to_database.load_users_to_sql manual__2025-03-30T23:35:10.238474+00:00 [queued]>
[2025-03-30T23:35:21.892+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-30T23:35:21.933+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_users_to_sql> on 2025-03-30 23:35:10.238474+00:00
[2025-03-30T23:35:21.960+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=226) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-30T23:35:21.967+0000] {standard_task_runner.py:72} INFO - Started process 228 to run task
[2025-03-30T23:35:21.965+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'import_users_to_database', 'load_users_to_sql', 'manual__2025-03-30T23:35:10.238474+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/etl_users.py', '--cfg-path', '/tmp/tmpp8tg0gqn']
[2025-03-30T23:35:21.973+0000] {standard_task_runner.py:105} INFO - Job 26: Subtask load_users_to_sql
[2025-03-30T23:35:22.130+0000] {task_command.py:467} INFO - Running <TaskInstance: import_users_to_database.load_users_to_sql manual__2025-03-30T23:35:10.238474+00:00 [running]> on host dd1836f126a3
[2025-03-30T23:35:22.394+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='azizjon' AIRFLOW_CTX_DAG_ID='import_users_to_database' AIRFLOW_CTX_TASK_ID='load_users_to_sql' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T23:35:10.238474+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-30T23:35:10.238474+00:00'
[2025-03-30T23:35:22.398+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-30T23:35:22.461+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-03-30T23:40:06.025+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-30T23:40:06.180+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-30T23:40:06.185+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=import_users_to_database, task_id=load_users_to_sql, run_id=manual__2025-03-30T23:35:10.238474+00:00, execution_date=20250330T233510, start_date=20250330T233521, end_date=20250330T234006
[2025-03-30T23:40:06.465+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-30T23:40:06.564+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T23:40:06.571+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
