[2025-03-30T21:53:38.259+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T21:53:38.371+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_table_if_not_exist.create_users_table scheduled__2025-03-21T00:00:00+00:00 [queued]>
[2025-03-30T21:53:38.421+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_table_if_not_exist.create_users_table scheduled__2025-03-21T00:00:00+00:00 [queued]>
[2025-03-30T21:53:38.425+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-30T21:53:38.484+0000] {taskinstance.py:2890} INFO - Executing <Task(SQLExecuteQueryOperator): create_users_table> on 2025-03-21 00:00:00+00:00
[2025-03-30T21:53:38.513+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=123) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-30T21:53:38.520+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'create_table_if_not_exist', 'create_users_table', 'scheduled__2025-03-21T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/create_sql_tables.py', '--cfg-path', '/tmp/tmpsxjsm880']
[2025-03-30T21:53:38.524+0000] {standard_task_runner.py:72} INFO - Started process 129 to run task
[2025-03-30T21:53:38.525+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask create_users_table
[2025-03-30T21:53:38.687+0000] {task_command.py:467} INFO - Running <TaskInstance: create_table_if_not_exist.create_users_table scheduled__2025-03-21T00:00:00+00:00 [running]> on host 3947a336792d
[2025-03-30T21:53:38.932+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='azizjon' AIRFLOW_CTX_DAG_ID='create_table_if_not_exist' AIRFLOW_CTX_TASK_ID='create_users_table' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-21T00:00:00+00:00'
[2025-03-30T21:53:38.937+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-30T21:53:38.997+0000] {sql.py:295} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS users (
                user_id INTEGER PRIMARY KEY,
                location VARCHAR(255),
                age INTEGER
            );
        
[2025-03-30T21:53:39.027+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-03-30T21:53:39.071+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-03-30T21:53:39.160+0000] {sql.py:511} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                user_id INTEGER PRIMARY KEY,
                location VARCHAR(255),
                age INTEGER
            );
        , parameters: None
[2025-03-30T21:53:39.309+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/common/sql/hooks/sql.py:470: DeprecationWarning: Import of fetch_all_handler from the '***.providers.common.sql.hooks' module is deprecated and will
be removed in the future. Please import it from '***.providers.common.sql.hooks.handlers'.
  result = self._make_common_data_structure(handler(cur))

[2025-03-30T21:53:39.319+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/common/sql/hooks/sql.py:471: DeprecationWarning: Import of return_single_query_results from the '***.providers.common.sql.hooks' module is deprecated and will
be removed in the future. Please import it from '***.providers.common.sql.hooks.handlers'.
  if return_single_query_results(sql, return_last, split_statements):

[2025-03-30T21:53:39.334+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/common/sql/hooks/sql.py:486: DeprecationWarning: Import of return_single_query_results from the '***.providers.common.sql.hooks' module is deprecated and will
be removed in the future. Please import it from '***.providers.common.sql.hooks.handlers'.
  if return_single_query_results(sql, return_last, split_statements):

[2025-03-30T21:53:39.340+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/common/sql/operators/sql.py:311: DeprecationWarning: Import of return_single_query_results from the '***.providers.common.sql.hooks' module is deprecated and will
be removed in the future. Please import it from '***.providers.common.sql.hooks.handlers'.
  if return_single_query_results(self.sql, self.return_last, self.split_statements):

[2025-03-30T21:53:39.382+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-30T21:53:39.385+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=create_table_if_not_exist, task_id=create_users_table, run_id=scheduled__2025-03-21T00:00:00+00:00, execution_date=20250321T000000, start_date=20250330T215338, end_date=20250330T215339
[2025-03-30T21:53:39.533+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-30T21:53:39.652+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-30T21:53:39.662+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-30T23:31:35.852+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T23:31:35.944+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_table_if_not_exist.create_users_table scheduled__2025-03-21T00:00:00+00:00 [queued]>
[2025-03-30T23:31:35.978+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_table_if_not_exist.create_users_table scheduled__2025-03-21T00:00:00+00:00 [queued]>
[2025-03-30T23:31:35.981+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-30T23:31:36.029+0000] {taskinstance.py:2890} INFO - Executing <Task(SQLExecuteQueryOperator): create_users_table> on 2025-03-21 00:00:00+00:00
[2025-03-30T23:31:36.052+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=123) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-30T23:31:36.057+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'create_table_if_not_exist', 'create_users_table', 'scheduled__2025-03-21T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/create_sql_tables.py', '--cfg-path', '/tmp/tmp1erjmtns']
[2025-03-30T23:31:36.062+0000] {standard_task_runner.py:72} INFO - Started process 125 to run task
[2025-03-30T23:31:36.063+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask create_users_table
[2025-03-30T23:31:36.286+0000] {task_command.py:467} INFO - Running <TaskInstance: create_table_if_not_exist.create_users_table scheduled__2025-03-21T00:00:00+00:00 [running]> on host dd1836f126a3
[2025-03-30T23:31:36.611+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='azizjon' AIRFLOW_CTX_DAG_ID='create_table_if_not_exist' AIRFLOW_CTX_TASK_ID='create_users_table' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-21T00:00:00+00:00'
[2025-03-30T23:31:36.614+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-30T23:31:36.744+0000] {sql.py:295} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS users (
                user_id INTEGER PRIMARY KEY,
                location VARCHAR(255),
                age INTEGER
            );
        
[2025-03-30T23:31:36.808+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 296, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 195, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 171, in _hook
    hook = self.get_hook(conn_id=conn_id, hook_params=self.hook_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 163, in get_hook
    connection = BaseHook.get_connection(conn_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_localhost` isn't defined
[2025-03-30T23:31:36.851+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=create_table_if_not_exist, task_id=create_users_table, run_id=scheduled__2025-03-21T00:00:00+00:00, execution_date=20250321T000000, start_date=20250330T233135, end_date=20250330T233136
[2025-03-30T23:31:36.968+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-30T23:31:36.972+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 8 for task create_users_table (The conn_id `postgres_localhost` isn't defined; 125)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 296, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 195, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 171, in _hook
    hook = self.get_hook(conn_id=conn_id, hook_params=self.hook_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 163, in get_hook
    connection = BaseHook.get_connection(conn_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_localhost` isn't defined
[2025-03-30T23:31:37.053+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-30T23:31:37.079+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
