[2025-04-10T18:51:03.434+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-10T18:51:03.503+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_users_to_database.load_users_to_sql manual__2025-04-10T18:51:00.097981+00:00 [queued]>
[2025-04-10T18:51:03.529+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_users_to_database.load_users_to_sql manual__2025-04-10T18:51:00.097981+00:00 [queued]>
[2025-04-10T18:51:03.533+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-10T18:51:03.570+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_users_to_sql> on 2025-04-10 18:51:00.097981+00:00
[2025-04-10T18:51:03.586+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=138) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-10T18:51:03.591+0000] {standard_task_runner.py:72} INFO - Started process 140 to run task
[2025-04-10T18:51:03.590+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'import_users_to_database', 'load_users_to_sql', 'manual__2025-04-10T18:51:00.097981+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/etl_users.py', '--cfg-path', '/tmp/tmp8bk4lxk1']
[2025-04-10T18:51:03.597+0000] {standard_task_runner.py:105} INFO - Job 85: Subtask load_users_to_sql
[2025-04-10T18:51:03.749+0000] {task_command.py:467} INFO - Running <TaskInstance: import_users_to_database.load_users_to_sql manual__2025-04-10T18:51:00.097981+00:00 [running]> on host 721ac7e631a9
[2025-04-10T18:51:05.701+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='azizjon' AIRFLOW_CTX_DAG_ID='import_users_to_database' AIRFLOW_CTX_TASK_ID='load_users_to_sql' AIRFLOW_CTX_EXECUTION_DATE='2025-04-10T18:51:00.097981+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-10T18:51:00.097981+00:00'
[2025-04-10T18:51:05.704+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-10T18:51:05.773+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-04-10T18:55:05.262+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-10T18:55:05.289+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-10T18:55:05.291+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=import_users_to_database, task_id=load_users_to_sql, run_id=manual__2025-04-10T18:51:00.097981+00:00, execution_date=20250410T185100, start_date=20250410T185103, end_date=20250410T185505
[2025-04-10T18:55:05.395+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-10T18:55:05.769+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-10T18:55:05.779+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
