[2025-03-30T21:59:01.303+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T21:59:01.345+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_users_to_database.load_users_to_sql manual__2025-03-30T21:58:55.710281+00:00 [queued]>
[2025-03-30T21:59:01.369+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_users_to_database.load_users_to_sql manual__2025-03-30T21:58:55.710281+00:00 [queued]>
[2025-03-30T21:59:01.371+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-30T21:59:01.410+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_users_to_sql> on 2025-03-30 21:58:55.710281+00:00
[2025-03-30T21:59:01.432+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=278) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-30T21:59:01.439+0000] {standard_task_runner.py:72} INFO - Started process 280 to run task
[2025-03-30T21:59:01.438+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'import_users_to_database', 'load_users_to_sql', 'manual__2025-03-30T21:58:55.710281+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/etl_users.py', '--cfg-path', '/tmp/tmpuou0qdem']
[2025-03-30T21:59:01.445+0000] {standard_task_runner.py:105} INFO - Job 33: Subtask load_users_to_sql
[2025-03-30T21:59:01.580+0000] {task_command.py:467} INFO - Running <TaskInstance: import_users_to_database.load_users_to_sql manual__2025-03-30T21:58:55.710281+00:00 [running]> on host 3947a336792d
[2025-03-30T21:59:02.980+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='azizjon' AIRFLOW_CTX_DAG_ID='import_users_to_database' AIRFLOW_CTX_TASK_ID='load_users_to_sql' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T21:58:55.710281+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-30T21:58:55.710281+00:00'
[2025-03-30T21:59:02.984+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-30T21:59:03.037+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-03-30T22:04:32.027+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-30T22:04:32.058+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-30T22:04:32.060+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=import_users_to_database, task_id=load_users_to_sql, run_id=manual__2025-03-30T21:58:55.710281+00:00, execution_date=20250330T215855, start_date=20250330T215901, end_date=20250330T220432
[2025-03-30T22:04:32.205+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-30T22:04:32.772+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T22:04:32.778+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
